\mainmatter

# (PART\*) INTRODUCTION {-}

# The Problem

> "Why did he die on Tuesday and not on Monday?"
>
> --- Douglas Zipes

The underlying premise in this question posed by Dr. Zipes is that the cardiac substrate can be *triggered* into an catastrophic maelstrom [@Zipes2006]. 
That trigger is oftentimes psychological in nature, and in the right setting, such as a scarred myocardium, can lead to electrical instability and ventricular arrhythmias [@Lown1979].
The reaction of the body to such stresses is thus a critical step in the pathogenesis of major adverse cardiovascular events.

Patients with psychiatric disease have an increased of cardiovascular disease and overall mortality [@Carney2002; @Boscarino2008].
Depression, for example, is the leading cause of disabilty in the world [@Friedrich2017b], and coronary artery disease (CAD) is the leading cause of death [@McAloon2016b]. 
The prevalence of depression is 20% in patients with CAD, and in those with comorbid depression and CAD, there is a 3-fold increase in cardiovascular mortality [@Jha2019; @Meijer2011].
Thus, understanding how the body reacts to stress can have implications in the the pathogenesis of the increased cardiovascular risk seen in psychological disease.

The purpose of this dissertation is to assess how physiological and psychological stress can be measured, and whether or not these measures of stress are clinically pertinent.
Measuring stress and stress reactivity requires a method to quantify disturbances of the neurocardiac axis, and assessing changes from both a neuropsychological and cardiac perspective [@Davis1993].
Leveraging different types of stress along the neurocardiac axis is important, such as the effect of myocardial ischemia, acute mental stress, chronic psychological stress, and systemic diurnal changes.

# The Approach

The suspected mechanism of behind stress reactivity is through dysfunction of the autonomic nervous system (ANS), particularly as there is an increased mortality with known ANS dysfunction [@LaRovere1998; @Stein2000].
Both psychological stress and myocardial ischemia are known to have a relationship with ANS dysfunction [@Carney2005], and the interaction between sympathetic and parasympathetic nervous activity is thus consequential.

To measure ANS dysfunction, a common surrogate is through electrocardiographic (ECG) changes based on sympathetic and vagal effects upon the sinoatrial node, or pacemaker, of the heart. 
The corresponding heart rate variability (HRV), and its mathematical derivatives, can thus inform us of the dynamic changes to autonomic tone [@Sassi2015].
By measuring autonomic tone during different stress, we can quantify the stress reactivity of the phenomenon and model its impact on clinically relevant factors, such as depression, cardiovascular disease, and major adverse cardiovascular events.
