# (PART\*) BACKGROUND {-}

1. ANS dysfunction
1. CAD and MPI and CFR
1. Psychological changes that effect ANS
1. 

# Review of the Literature



# Clinical Relevance


Burden of Depression in Coronary Artery Disease: An Untreated Epidemic

Depression is the leading cause of disability in the world,2 and CAD is the leading cause of death.3 Depression is estimated to occur in over 300 million people, which accounts for roughly 4% of the global population.2 The estimated yearly economic burden of depression in US is $210 billion dollars and the estimated direct and indirect costs of CAD is $204 billion, with the cost of both continuing to climb.34,35 In individuals with CAD, the prevalence of depression is up to 20%.4 In comorbid depression and CAD, there is a 3-fold increase in the incidence of secondary cardiovascular disease (CVD) outcomes;6 however only in the last several years has depression been recognized as an additional prognostic marker of mortality.5 The rate of increased mortality in CAD with depression has remained unchanged over the past 35 years.6 

Critical Gap in the Evidence Linking Depression Treatment with CVD Risk Reduction

Although interventions such as cognitive behavioral therapy and antidepressants are well-proven in reducing depressive symptoms, their impacts are only modest in CAD patients, and they do not impact event-free survival.7 Although the American College of Cardiology recommends depression should be routinely screened for in patients with cardiovascular disease,4 there is limited evidence that this leads to an improvement in overall mortality.8 More research is needed to understand the potential therapeutic mechanisms underlying depression and CAD1 in order to develop more effective therapies for the high-risk individuals in which both occur together. Our key premise for this investigation is that autonomic mechanisms can help fill this critical gap and provide insight into future novel, more effective therapies for both depression and CAD.

Autonomic Nervous System Plays an Important Mechanistic Role in both Depression and CAD

Dysfunction of the autonomic nervous system (ANS) has been found to occur in diseases of both the brain and heart, and may also underly somatic symptoms and vasomotor abnormalities observed in depression.36  Autonomic dysfunction occurs at multiple levels, from central neurological processes to peripheral cardiovascular reflexes.37 This includes vagal withdrawal in depression and heightened sympathetic tone in cardiovascular disease, for example. Depression has been linked to dysregulation of the ANS though increased levels of catecholamines,38 increased cardiovascular reactivity to stress,39 and decreased baroreflex sensitivity.40 The heart itself harbors an intrinsic cardiac nervous system that responds to changes in autonomic tone, such as in myocardial ischemia and infarction (MI), by changing heart rate, strength contraction, or the speed of nerve conduction.32,41 

Study of ANS-related mechanisms may inform future therapies. Interventions targeting ANS dysfunction show improved symptom burden in both depression and CAD and warrant additional research.10 For example, the vagal nerve activity may protect against ventricular fibrillation,42 and vagal nerve stimulation has been shown to relieve angina pectoris and cardiac arrhythmias.12,13 Vagal nerve stimulation (VNS) is also effective in treatment-resistant depression.11 Dr. Shah has studied non-invasive VNS in PTSD and found that it blunts the sympathetic response to stress.43 In summary, ANS dysfunction occurs in both depression and CAD, and research in this area is important as neuromodulation therapies such as non-invasive VNS are studied and become increasingly available.

Advances in Electrocardiography can Assess Autonomic Dysfunction

A novel ECG-based biomarker for ANS dysfunction, Dyx, has surfaced in the last several years, and is actively being investigated by the company HeartTrends, LLC for its clinical application in CAD risk stratification. Dyx is an advanced heart rate variability (HRV) metric that strongly associates with myocardial ischemia and future adverse outcomes.19,20 HRV is an accepted measure of cardiac autonomic activity, which is the integration of the multiple levels of sympathetic and parasympathetic efferent input at the level of the sinoatrial node. 15,16 Dyx is derived from heart rate time series analysis and measures the variability and randomness of the heart rhythm. Dyx is generated through the multipole method analysis of Poincaré plot, in which beat-to-beat (RR) interval lengths are plotted as a function of prior RR intervals to form an ellipse, as seen in our prior work (Figure D1).44 Dyx is calculated as the ratio of the kurtosis along the y-axis and the x-axis of the ellipse, better capturing the density of heart beats and thus including non-linear features of heart rate dynamics.17,18 Low Dyx predicts ventricular dysrhythmia and cardiovascular mortality after myocardial infarction, with a hazard ratio of 2.4 (95% CI 1.5 – 3.8).18,19 In addition, individuals with chest pain and low Dyx had an odds ratio of 8 (95% CI 3.1 – 23.9) for having abnormal exercise stress test results.20,21 This makes Dyx a strong candidate for assessing ANS dysfunction in our proposal.
