# (PART\*) BACKGROUND {-}

# Clinical Importance

Psychological stress is increasingly recognized as an important potentially modifiable risk factor for cardiovascular disease [@Steptoe2012].
Psychiatric disease leads to an increase cardiovascular disease and overall mortality.
PTSD, for example, has twice the hazard ratio for not only progressive coronary artery disease, but also for overall mortality [@Boscarino2008].
Depression and loneliness have a distinct increase in all-cause mortality [@Steptoe2013a], and almost twice twice the risk of coronary artery disease [@Ford1998].
Specifically, depression is the leading cause of disability worldwide, estimated to be prevalent in over 300 million people, which accounts for roughly 4% of the global population [@Friedrich2017b].
In the United States, the estimated economic burden of depression is $210 billion dollars as of 2010, doubling in cost from 2000 [@Greenberg2015b], suggesting a worsening, growing burden.
CAD on the other hand remains the leading cause of death [@McAloon2016b]. 
This corresponds with approximately $204 billion dollars of estimated direct and indirect costs, with both continuing to climb [@Benjamin2018c]. 

In individuals with CAD, the prevalence of depression is estimated to be 20%, and in those with comorbid depression and CAD, there is over a 3-fold increase in cardiovascular mortality [@Jha2019; @Meijer2011].
This increased risk of mortality in CAD with depression has remained unchanged over the past 35 years [@Carney2017], as only in recent years has depression been considered an additional prognostic marker of mortality in CAD [@Lichtman2014].

Although interventions such as cognitive behavioral therapy and antidepressants are well-proven in reducing symptoms of psychological distress, their impacts are only modest in patients with CAD, and they do not impact event-free survival [@Berkman2003].
Although the American College of Cardiology recommends depression should be routinely screened for in patients with cardiovascular disease, there is limited evidence that this leads to an improvement in overall mortality [@Kronish2019].
More research is needed to understand the therapeutic mechanism underlying psychological distress and CAD [@Carney2017], as there are no effective therapies for these high-risk individuals in comorbid patients.

The causal mechanism is suspected to be through ANS dysfunction, as this has been found to occur in both diseases of the brain and heart [@Davis1993].
Not only are somatic symptoms of psychological stress predictive of cardiovascular mortality, but they may be explained by changes seen in HRV [@Smolderen2017; @Shah2021a].
Similarly, abnormalities in myocardial perfusion are related to and may be predated by abnormalities in HRV [@Shah2020]. 
Thus, investigating the role of autonomic dysfunction in neurocardiac disorders is both mechanistically plausible and may allow for the development of efficacious therapeutic interventions.

# Relevant Literature

The heart itself harbors an intrinsic cardiac nervous system that responds to changes in autonomic tone, such as in myocardial ischemia and infarction, by changing chronotropic, inotropic, and dromotropic responses [@Armour1999; @Zipes1990].
Autonomic dysfunction occurs at multiple levels, from central neurological processes to cardiovascular reflexes [@Abboud2011]. 
This includes vagal withdrawal seen in depression and heightened sympathetic tone seen in PTSD or cardiovascular disease.
Depression, for example, has been linked to dysregulation of the ANS through changes in levels of catecholamines [@Veith1994b], increased cardiovascular reactivity to stress [@Hughes2008], and decreased baroreflex sensitivity [@Davydov2007].

ANS-related mechanisms are important as they are related to both cardiac and neuropsychological disorders.
The autonomic innervation of the heart has been show repeatedly to play a critical role in myocardial ischemia [@Minisi1991; @Pauziene2016; @Ardell2016a].
Historically stellectomy was found to reduce angina pectoris and ventricular dysrhythmias [@Schwartz2017a].
Modern interventions have shown to improve symptom burden not only in CAD, but also in depression [@Penninx2017].
Vagal nerve stimulation has been shown to relieve cardiac arrhythmias, and has been effective against treatment-resistant depression [@Zhang2011a].
In PTSD, non-invasive vagal nerve stimulation has also been found to blunt the sympathetic response to stress [@Gurel2019a].
These relationships between chronic psychological stress, cardiac perfusion and arrhythmias, and the ANS help to establish the important influences on the neurocardiac axis.

HRV has been shown to be an effective ECG-based biomarker for ANS dysfunction. 
HRV is an accepted measure of autonomic activity, as it is an integration of sympathetic and parasympathetic efferent input at the level of the sinoatrial node [@Saul1990].
For example, the non-linear HRV marker of *Dyx* has been shown to predict ventricular dysrhythmia and cardiovascular mortality after myocardial infarction, with a hazard ratio of 2.4 (95% CI 1.5 -- 3.8) [@Jørgensen2016]. 
In addition, individuals with chest pain and abnormal *Dyx* had an odds ratio of 8 (95% CI 3.1 -- 23.99) for abnormal exercise stress test [@Goldkorn2015b].
Not only does HRV correlate well with cardiovascular disease, but is strongly correlated with depression [@Stein2000]. 
This relationship between psychological stress, cardiovascular disease, and the autonomic nervous system is thus an appropriate candidate for further investigation, particularly in justifying the clinical utility in measuing autonomic dysfunction [@Carney2005].
In addition to chronic mental stress, acute mental stress has become a more common way of assessing physiological reactivity. 
Mental stress has been shown to associate with chronic psychological stressors [@Petrowski2016], and can also lead to the development of myocardial ischemia [@Arri2016]. 
This phenomenon, known as mental stress-induced myocardial ischemia (MSIMI), is an important reaction to stress that has been shown to predict long-term clinical outcomes [@Vaccarino2018].
HRV has been shown that to associate with acute mental stress [@Castaldo2015], but the relationship between MSIMI has not yet been determined.

The circadian rhythm in autonomic dysfunction is also relevant. 
The response to the stress of changing from sleep to wake has been seen to associate with increased cardiovascular mortality.
There is an increased frequency of sudden cardiac death based on time of day, usually peaking between 6 AM and 10 AM [@Muller1999; @Boudreau2011], with a secondary peak between 6 PM and 8 PM [@Mulcahy1988]. 
There is a circadian pattern to autonomic outflow, melatonin, cortisol, and circulating catecholamines which could increase vulnerability to ischemia and cardiac death during morning hours [@Boudreau2011; Scheer2010].
The relationship of circadian changes in HRV and myocardial perfusion has been shown to be related [@Shah2020], but how circadian changes may be important in psychological stress and overall mortality is not yet known.
Thus, studying circadian autonomic variability may reveal insights into the diurnal nature of clinical disease.

# Specific Aims {#aims}

The response to both physiological and psychological stress can be markers of overall cardiovascular adaptability. The following aims help to assess the clinical importance of stress reactivity as measured by disturbances to the neurocardiac axis at different levels of cardiovascular risk. 

**AIM I --- Autonomic mechanisms underlying psychological stress.**

1. Examine the effect of acute mental stress on sympathovagal balance and cardiac autonomic function in a cohort of participants with CAD undergoing a laboratory based mental stress challenge. 
*We hypothesize that heart rate is higher and HRV is lower during both stress and recovery phases of acute mental stress challenge as compared to the rest phase.*
1. Examine the relationship of cardiac autonomic dysfunction measured in the setting of acute mental stress challenge with depression and posttrauamtic stress disorder in a cohort of participants with CAD undergoing a laboratory based mental stress challenge. 
*We hypothesize that lower short-term HRV during acute stress associate with depression and PTSD.*
1. Examine the relationship of circadian cardiac autonomic variability over 24 hours with depression and PTSD in a cohort of male veteran twins.
*We hypothesize that lower circadian variation in HRV (amplitude) and 24-hour mean HRV (mesor) associate with depression and PTSD.*

**AIM II --- Autonomic mechanisms underlying ischemic heart disease.** 

1. Examine the relationship of baseline resting cardiac autonomic dysfunction with obstructive coronary artery disease (>70% stenosis) in a cohort of high-risk patients undergoing coronary angiography. 
*We hypothesize that short-term autonomic metrics are lower in subjects with obstructive, epicardial disease compared to those without evidence of obstructive CAD.*
1. Examine the acute effect of revascularization of obstructive coronary artery disease on short-term cardiac autonomic function compared to changes that otherwise occur by angiography alone, without intervention. 
*We hypothesize that in subjects undergoing revascularization of the coronary arteries, short-term HRV is lower after revascularization as compared to before revascularization and also compared to HRV during angiography.*
1. Examine the relationship of early morning and circadian autonomic variability with conventional myocardial ischemia and flow reserve in a cohort of male veteran twins. 
*We hypothesize that lower early morning HRV and circadian HRV variability associate with greater conventional myocardial ischemia and lower myocardial flow reserve.*
1. Examine the relationship between acute changes in cardiac autonomic function during mental stress challenge and mental stress induced myocardial ischemia in a cohort of participants with stable CAD. 
*We hypothesize that mental stress-induced decreases in HRV associate with an increased odds of mental stress-induced myocardial ischemia.*  

**AIM III --- Autonomic mechanisms underlying the risk of major adverse cardiovascular events.**

1. Examine the relationship of early morning and circadian autonomic variability with CVD and all-cause mortality in a cohort of male veteran twins. 
*We hypothesize that lower early morning HRV and circadian HRV variability associate with an increased hazard for overall and cardiovascular mortality.*
1. Examine the relationship between acute changes in cardiac autonomic function during mental stress challenge and future major adverse cardiovascular events in a cohort of participants with stable CAD.
*We hypothesize that mental stress-induced decreases in HRV associate with an increased hazard for cardiovascular mortality and recurrent cardiovascular events.*

