# (PART\*) METHODS {-}

# Specific Aims {#aims}

The response to both physiological and psychological stress can be markers of overall cardiovascular adaptability. The following aims help to assess the clinical importance of stress reactivity as measured by disturbances to the neurocardiac axis at different levels of cardiovascular risk. 

**AIM I --- Autonomic mechanisms underlying psychological stress.**

1. Examine the effect of acute mental stress on sympathovagal balance and cardiac autonomic function in a cohort of participants with CAD undergoing a laboratory based mental stress challenge. 
*We hypothesize that heart rate is higher and HRV is lower during both stress and recovery phases of acute mental stress challenge as compared to the rest phase.*
1. Examine the relationship of cardiac autonomic dysfunction measured in the setting of acute mental stress challenge with depression and posttrauamtic stress disorder in a cohort of participants with CAD undergoing a laboratory based mental stress challenge. 
*We hypothesize that lower short-term HRV during acute stress associate with depression and PTSD.*
1. Examine the relationship of circadian cardiac autonomic variability over 24 hours with depression and PTSD in a cohort of male veteran twins.
*We hypothesize that lower circadian variation in HRV (amplitude) and 24-hour mean HRV (mesor) associate with depression and PTSD.*

**AIM II --- Autonomic mechanisms underlying ischemic heart disease.** 

1. Examine the relationship of baseline resting cardiac autonomic dysfunction with obstructive coronary artery disease (>70% stenosis) in a cohort of high-risk patients undergoing coronary angiography. 
*We hypothesize that short-term autonomic metrics are lower in subjects with obstructive, epicardial disease compared to those without evidence of obstructive CAD.*
1. Examine the acute effect of revascularization of obstructive coronary artery disease on short-term cardiac autonomic function compared to changes that otherwise occur by angiography alone, without intervention. 
*We hypothesize that in subjects undergoing revascularization of the coronary arteries, short-term HRV is lower after revascularization as compared to before revascularization and also compared to HRV during angiography.*
1. Examine the relationship of early morning and circadian autonomic variability with conventional myocardial ischemia and flow reserve in a cohort of male veteran twins. 
*We hypothesize that lower early morning HRV and circadian HRV variability associate with greater conventional myocardial ischemia and lower myocardial flow reserve.*
1. Examine the relationship between acute changes in cardiac autonomic function during mental stress challenge and mental stress induced myocardial ischemia in a cohort of participants with stable CAD. 
*We hypothesize that mental stress-induced decreases in HRV associate with an increased odds of mental stress-induced myocardial ischemia.*  

**AIM III --- Autonomic mechanisms underlying the risk of major adverse cardiovascular events.**

1. Examine the relationship of early morning and circadian autonomic variability with CVD and all-cause mortality in a cohort of male veteran twins. 
*We hypothesize that lower early morning HRV and circadian HRV variability associate with an increased hazard for overall and cardiovascular mortality.*
1. Examine the relationship between acute changes in cardiac autonomic function during mental stress challenge and future major adverse cardiovascular events in a cohort of participants with stable CAD.
*We hypothesize that mental stress-induced decreases in HRV associate with an increased hazard for cardiovascular mortality and recurrent cardiovascular events.*

# Study Design

## Population Characteristics and Study Overview

### Emory Cardiovascular Biobank (*Biobank*)

The *Biobank* studies major cardiovascular events, and also evaluates additional biomarkers for inflammation, cardiac injury, and genetics, with the goal of identifying novel factors associated with the pathobiological process and treatment of CVD [@Ko2017].
All patients aged 18 years and older undergoing cardiac catherization were included. 
During the index cardiac catheterization, additional measures including lifestyle factors, psychological status, medical comorbidities, revascularization and previous procedures were ascertained via patient interview and chart review. 
Additionally, ambulatory ECG was collected with the VivaLNK patch, which was placed on the morning of cardiac catheterization and removed after catheterization for up to 24 hour of data recording.
Patients were excluded if they have congenital heart disease, severe valvular heart disease, severe anemia, a recent blood transfusion, myocarditis, history of active inflammatory disease, cancer or are unable or not willing to provide consent (approximately 5%). 
Those that are found to have atrial fibrillation or have >20% ectopic beat burden or noise, as well as those that are pacer dependent were excluded.
Those with known CAD were also excluded.

### Emory Twins Study (*Twins*)

The *Twins* is a longitudinal cohort study designed to examine the relationship of depression and PTSD with myocardial perfusion abnormalities, with follow-up focused on CVD outcomes and changes in perfusion over time. In addition, the study design allows for studying the relationship between myocardial perfusion with autonomic function, measured hourly over the course of 24 h, in individuals without known ischemic heart disease. 
Subjects were drawn from the Emory Twin Study, which recruited middle-aged male twin pairs from the Vietnam Era Twin Registry [@Shah2013; @Vaccarino2009a; @Goldberg2002].
Pairs of twins were examined at the Emory University General Clinical Research Center, and all data collection occurred during a 24-hour admission under controlled conditions. 
The twins in each pair maintained a nearly identical schedule, with all data collection beginning and ending at the same time. 
The twins arrived at 11 AM, with ECG recording started at approximately 1 PM, questionnaires and exam performed between 2 and 4 PM, dinner at 5 PM, bedtime at 10 PM, wake-up time at 6:30 AM, and PET scans performed between 8 and 10 AM the following morning. 
The twins were followed longitudinally for follow-up events, including review of national registries, which were adjudicated.
Subjects were excluded from analysis if they were unable to complete pharmacological stress testing. 

### Mental Stress Ischemia Mechanisms and Prognosis, Myocardial Infarction and Mental Stress (*MIMS/MIPS*)

The study design has been described prior, and is the same between the two cohorts [@Hammadah2017a].
The *MIMS* cohort included participants with recent myocardial infarction within the 8 months prior to enrollment who were younger than 61 years of age at time of enrollment. 
The *MIPS* cohort included patients with stable CAD diagnosed via coronary angiogram, documented MI, or positive nuclear stress test. 
All patients underwent mental stress test and physical stress test using either treadmill or regadenosine, and were randomly assigned to complete one and then the other in two separate visits within a week.
During the initial visit, medical history and psychological assessments were performed as well.
During the mental stress testing, all patients had ECG recordings made of variable duration.
Patients were followed longitudinally for 3-5 years for follow-up events, which were adjudicated.
Patients were excluded for having acute coronary syndrome or decompensated heart failure, severe psychiatric conditions other than depression, pregnancy, uncontrolled high blood pressure, or contraindications to pharmacological stress testing. 

## Measurements

### Electrocardiography Measures

In all three cohorts, ECG data were collected and analyzed using different ECG acquisition strategies and signal processing methods. As described, in the *Biobank*, ECG was collected through a single, bipolar lead using the VivaLNK patch, with data being recorded for up to 24 h. In the *Twins*, ambulatory ECG was collected through Holter monitor (GE Marquette SEER digital system; GE Medical Systems, Waukesha, Wisconsin) for 24 h. Holter monitor was also used in the *MIMS/MIPS*, however the recording time was only for several hours.

Variations in heart rate can be assessed by a number of mathematical measures, usually divided into the time and frequency domains [@TaskForceoftheESCandNAS1996a].
HRV was calculated through the Physionet Cardiovascular Signal Toolbox [@Vest2018], which is an open-source MATLAB software for analyzing ECG signal.
Time domain measures we used include the RR interval duration (converted to heart rate in beats-per-minute), the standard deviation of normally conducted RR intervals (SDNN), the root mean square of successive differences in normally conducted RR intervals (RMSSD), and the proportion of normally conducted RR intervals that differ by more than 50 ms divided by the total number of normally conducted RR intervals (PNN50). 
Frequency-domain measures computed through power spectral analysis categorize variability as very low frequency (VLF, 0.0033 to <0.04 Hz), low frequency (LF, 0.04 to <0.15 Hz) or high frequency (HF, 0.15 to 0.40 Hz) [@Akselrod1981].
These frequency categories reflect autonomically mediated heart rate responses to physiologic stimuli, including influences of the renin-angiotensin-aldosterone system, baroreceptor activity, and respiration [@Akselrod1981].
The sympathetic and parasympathetic nervous systems influence them to different degrees. 
HF reflects primarily parasympathetic nervous system activity, while LF reflects both sympathetic and parasympathetic activity [@ReyesdelPaso2013].
Total power HRV is a nonspecific global measure. 
RMSSD is an approximate correlate of HF, and SDNN is an approximate correlate of TP, supporting the physiological basis of these markers.[Electrophysiology1996b]
Acceleration capacity and deceleration capacity were also included where available, based on signal quality and recording length, as they also reflect clinically relevant sympathetic and vagal activity [@Bauer2006c].
These metrics are well-known as physiologic markers of acute and chronic stress, and measure slightly different aspects of autonomic nervous system function.
HRV was also analyzed hourly through the commercial HeartTrends algorithm (Lev-El Diagnostics Ltd, Israel), which generated the *Dyx* measure.
*Dyx* is derived from heart rate time series analysis and measures the variability and randomness of the heart rhythm. 
*Dyx* is generated through the multipole method analysis of Poincaré plot, in which beat-to-beat (RR) interval lengths are plotted as a function of prior RR intervals to form an ellipse, as seen in Figure \@ref(FigurePoincare).
*Dyx* is calculated as the ratio of the kurtosis along the y-axis (long-term variability) and the x-axis (beat-to-beat random variation) of the ellipse, and higher values indicate more beat-to-beat randomness and/or decreased variability [@Olesen2005; @Lewkowicz2002].

In addition to summary and hourly assessments of HRV, diurnal rhythms were examined using cosinor metrics within the *Twins*, as seen in Figure \@ref(FigureCosinor) [@Refinetti2007]. 
Morphological assessment of ECG changes were also performed in the *MIMS/MIPS* with T-wave area. The frequency domain HRV metrics were log-transformed, and then all metrics were normalized to allow for comparison.


### Psychological Measures

In all cohorts, chronic psychological variables were measured through patient interviews, using the Structured Clinical Interview for Diagnostic and Statistical Manual of Mental Disorders, 4th Edition (DSM-IV) criteria [@First2004] for the diagnosis of both depression and posttraumatic stress disorder (PTSD).
In the *Biobank*, depressive symptoms were assessed via the 9-question Primary Care Evaluation of Mental Disorders Brief Patient Health Questionnaire (PHQ-9) [@Kroenke2001].
Moderate-severe depression is considered when the PHQ-9 score is 10 points or higher (out of 27), with this cutpoint having a sensitivity and specificity of 88% for major depression. 
Within the *Twins* and *MIMS/MIPS* cohorts, depressive symptomers were assessed with Beck's Depression Inventory, which includes 21 items with 4 statements scored 0-3, with higher scores indicating higher severity of depression [@Beck1988].
A cut-off of $\geq$ 14 points was used to identify patients with moderate-to-severe depressive symptom burden.

In the *MIMS/MIPS* cohort, there was a separate protocol for acute mental stress challenge. 
Patients were initially allowed to rest for 30 minutes in a calm, quiet, dimly lit, and temperature-regulated room.
After the resting period, mental stress was induced by a standardized public speaking task, as previously described [@DavidGoldberg1996].
The patients were asked to imagine a real-life stressful situation, such as a close relative having been mistreated in a nursing home, and then asked to make up a realistic story around this scenario.
They were given two minutes to prepare the statement, and three minutes to present it in front of a video camera and an audience.
The patients were told that the speech would be evaluated for content, quality, and duration.

### Cardiac Measures

All cohorts underwent imaging of the heart through different modalities, which all assess complementary aspects of myocardial blood flow. 

The *Biobank* used direct coronary angiography through cardiac catheterization.
Obstructive CAD was defined as $\ge$ 70% stenosis or hemodynamic significance by fractional flow reserve. 
Coronary angiography was used to determine the Gensini score, which is a visual estimation of luminal narrowing in multiple segments based on a modified form of the American Heart Association classification of the coronary tree by trained cardiologists [@Gensini1983].
Coronary angiography was also evaluated using the Coronary Artery Surgery Study (CASS), which evaluates the number of major epicardial vessels that have a certain percent stenosis, e.g. the CASS-50 score determines the number of vessels with $\ge$ 50% stenosis [@Ringqvist1983].
Importantly, direct coronary angiography is limited to visualization of the large, epicardial conduit vessels.

The *Twins* study used MPI using underwent MPI using nitrogen-13-ammonia positron emission tomography (PET) with adenosine as the pharmacologic stressor.
Adenosine doses were calculated to induce maximal coronary vasodilation [@Vaccarino2011]. 
Areas of diminished uptake indicate reduced capacity to maximally vasodilate, thereby causing relative coronary hypoperfusion. 
Images were visually interpreted by experienced cardiologists and radiologists with training in nuclear cardiology. 
Quantitative analysis was performed with the Emory Cardiac Toolbox to generate: a) coronary flow reserve (CFR) for absolute myocardial blood flow during stress and rest, and b) the stress total severity score (STSS), which measures the sum of the number of standard deviations below the expected value for each pixel compared to a database of normal controls [@Hutchins1990]. 
CFR was defined as the ratio of mean stress to rest myocardial blood flow (mL/min/g), and low CFR was defined as a ratio $<$ 1.5 [@Gould2018a].
Abnormal MPI findings were defined as $>$ 5% MPI deficit.
For generalizability, semi-quantitative assessments were used. 

In the *MIMS/MIPS*, MPI was also used but with single-photon emission computered tomography (SPECT), using sestamibi radio-labelled with Technetium-99. 
SPECT was performed at rest, after mental stress, and after physical stress (either exercise or pharmacological). 
Myocardial perfusion abnormalities were quantified using the Emory Cardiac Toolbox software, similar to the *Twins*, and semi-quantitative assessments were determined.

## Sample Size and Power Considerations

The subjects for the *Biobank* were enrolled from September 2019 to February 2020, however further enrollment was limited due to the COVID-19 pandemic. 
It was expected that approximately 200 patients would be needed for adequate power, but due to limitations, the analyses were conducted on available data.
The enrollment for *MIMS/MIPS* and *Twins* was completed prior to the initiation of this analysis, and provided a robust population to expand upon and answer the specific aims.

# Analysis

Statistical analysis was performed using R 4.0.0 (R Core Team 2020, Vienna, Austria). 
The analytical approach was guided by the specific aims (Section \@ref(aims)). 

## Clinical Characteristics

In the *Biobank*, HRV was summarized over the recording length and at 15-30 minute intervals at the time of coronary angiography. 
In the *Twins*, HRV was computed hourly, including *Dyx*. 
The 24-hour data was used to generate cosinor statistics using published software [@Shah2020d]. 
In the *MIMS/MIPS*, HRV was computed for each phase of the mental stress challenge. 
Power spectral density measures of HF, LF, and VLF HRV were log-transformed for normal distribution.
Each of the clinical cohorts was described by clinical covariates, including frequency of comorbid diseases and summary statistics of continuous measures.

## Myocardial Ischemia

The purpose of **Aim I** was to identify the relationship of autonomic dysfunction with CAD, as measured by both coronary angiography and MPI. 
Within the *Biobank*, summary HRV metrics were compared between those with obstructive CAD versus nonobstructive CAD using the Wilcoxon rank sum test. 
HRV was then assess in a similar manner between those receiving revascularization and those that did not. 
HRV was segmented by timing of coronary angiography. 
HRV was compared at the start of catheterization (or initial intervention in those that were revascularized) to the 30 minutes before the procedure, by intervention status. 

To evaluate the relationship with myocardial perfusion, HRV was also assessed within the *MIMS/MIPS* cohort, which had both mental and physical stress MPI as outcomes. 
Logistic regressions were used with HRV during stress and rest as the exposures, not adjusted for clinical covariates. 
The area under the receiver-operator characteristic curves were generated. 

```{r}
fit <- 
	twins_models$equipment$lin_lf_adjusted %>%
	filter(outcomes == "global_cfr" & level == 7 & test_num == 10) %>%
	pull(fit) %>%
	.[[1]] %>%
	pluck("fit")

extract_eq(fit, wrap = TRUE, terms_per_line = 4)
```

Within the *Twins*, similar analyses were performed with MPI and hourly HRV. Early morning, approximately 7 AM, HRV was used based on previous work suggesting the strong temporal relationship of HRV with clinical outcomes [@Shah2020]. 
Generalized linear mixed-effects models with Laplace approximations were used to account for clustering within twin pairs and within repeat study visits [@Carlin2005a].
Coronary flow reserve was treated as the outcome variable in linear models, and abnormal MPI was treated as the outcome variable in logistic models. 
With the mixed-effects model, with random effects or conditioning for both twin pair status and repeat study visits. 
The models were sequentially adjusted for demographic variables (age, BMI, and race), and then for cardiovascular risk factors (smoking, hypertension, cardiovascular disease).
HRV was summarized as cosinor metrics of MESOR (midline estimating statistic of rhythm), amplitude, and acrophase. 
These metrics were treated as exposures, with CFR and MPI as outcomes, in mixed effects models as above.

## Psychological Stress

The purpose of **Aim II** was to establish the relationship between psychological stress and autonomic dysfunction.
Acute psychological stress was defined as the mental stress challenge in the *MIMS/MIPS* cohorts. Chronic psychological stress was defined as diagnoses of depression and PTSD, and/or symptom burden.

In the *Biobank*, the distribution of HRV was compared between those with depression, as measured by PHQ-9, using Wilcoxon rank sum test. 
In the *Twins*, using the above described generalized linear mixed-effects models, regression analysis was performed with early morning HRV as the exposure and either PTSD or depression as the outcome. 
Sequential adjustment was performed for demographic factors and cardiovascular risk factors. 
Cosinor metrics were also used as additional exposure variables in additional mixed-models.

The *MIMS/MIPS* cohort offered the opportunity to assess both acute and chronic psychological stress. 
The distribution of HRV was visually compared between phases of the mental stress challenge for all subjects.
HRV was then analyzed within subjects by comparing the rest phase to the both the stress and recovery phase using paired T-test.
The distribution of HRV was then compared by phase in those with MSIMI and those without MSIMI using the Wilcoxon rank sum test.
Logistic regression models were used with PTSD and depression as outcomes and HRV by stress phase as exposures, without adjustment, and concordance statistics were generated.
Logistic regression models were then built with MSIMI as the outcome and stress HRV as the exposure, along with concordance statistics.
These models were sequentially adjusted for demographic factors (age, BMI, sex, race), cardiovascular risk factors (smoking, hypertension, diabetes, hyperlipidemia), known cardiovascular disease (coronary/peripheral artery disease), and then with chronic psychological stress (depression, PTSD). 

## Clinical Outcomes

The purpose of **Aim III** was to evaluate the role of autonomic dysfunction in clinical outcomes, and understand the effect of autonomic dysfunction on the relationship between outcomes and both psychological stress and myocardial ischemia. Clinical outcomes were available in the *Twins* and *MIMS/MIPS* cohorts. Proportional hazard assumptions were assessed visually in both cohorts.

The clinical outcomes of interest were overall mortality and death by cardiovascular disease in the *Twins*. 
Early morning HRV was treated as the exposure, with the survival time before censoring event as the outcome in Cox proportional hazard models. 
The models were sequentially adjusted for myocardial ischemia, demographic factors (age, BMI, race), cardiovascular factors (known cardiovascular disease, hypertension, diabetes, smoking), and psychological factors (depression, PTSD). 
In a similar fashion, cosinor metrics for HRV were used as exposure variables in models that were sequentially adjusted as above. 

In the *MIMS/MIPS*, the clinical outcomes of interest were overall mortality, cardiovascular mortality, and recurrent cardiovascular events including myocardial infarction or revascularization. 
Cox proportional hazard models were used for both overall and cardiovascular mortality. 
Recurrent event analysis used proportional hazard models with strata for events and individuals using marginal models, Prentice-Williams-Peterson models (both total and gap time), and Anderson-Gill models [@Amorim2015a]. 
These models were sequentially adjusted for demographic factors (age, BMI, sex, race), cardiovascular risk factors (smoking, hypertension, diabetes, hyperlipidemia), known cardiovascular disease (coronary/peripheral artery disease), and then with chronic psychological stress (depression, PTSD). 

